# Generated by Django 3.0.6 on 2020-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(help_text='Please enter your SUrname here', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Please select male or female', max_length=10)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'Yes')], max_length=4)),
            ],
        ),
    ]
