# Generated by Django 3.0.6 on 2020-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='applicant_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='coapplicant_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='credit_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='dependant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], help_text='Please indicate if you are a graduate or not', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='loan_amount_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Semiurban', 'Semiurban')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='self_employed',
            field=models.CharField(help_text="Please indicate with a 'Yes' or 'No'", max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Please select male or female', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='lastname',
            field=models.CharField(help_text='Please enter your Surname here', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
    ]
