# Generated by Django 3.0.6 on 2020-05-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0002_auto_20200525_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvals',
            new_name='Approval',
        ),
    ]
