# Generated by Django 3.0.6 on 2020-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0004_auto_20200623_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='dependents',
        ),
    ]
