# Generated by Django 3.0.6 on 2020-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0005_remove_approval_dependents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='self_employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="Please indicate with a 'Yes' or 'No'", max_length=5, null=True),
        ),
    ]
