# Generated by Django 3.0.6 on 2020-06-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0006_auto_20200624_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='lastname',
        ),
    ]
